/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Services/Platform_Types.h"
#include "../Services/stm32f103c6.h"
#include "../MCAL/Inc/GPIO.h"
#include "../MCAL/Inc/EXTI.h"
#include "../HAL/Inc/LCD.h"
#include "../HAL/Inc/keypad.h"
#include "../HAL/Inc/SevenSegment.h"


GPIO_PinConfig_t LED = {GPIOA,GPIO_PIN_15,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};

void Clock_Init(void){
	//Enable CLock on Port A and Port B
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
	RCC_AFIO_CLK_EN();
}

void PrintHandlerLCD(void){
	HAL_LCD_WriteString("IRQ EXTI9 happened ;)");
	MCAL_GPIO_TogglePin(&LED);
}

int main(void)
{
	Clock_Init();

	MCAL_GPIO_Init(&LED);

	EXTI_PinConfig_t Button = {EXTIPA0,EXTI_TRIGGER_RISING,EXTI_IRQ_ENABLE,PrintHandlerLCD};
	MCAL_EXTI_Init(&Button);

	HAL_LCD_Init();
	HAL_KEYPAD_Init();
	HAL_7_SEGMENT_Init();

    /* Replace with your application code */

	uint8_t CharToPrint;

    while (1)
    {

		CharToPrint = HAL_KEYPAD_GetButtonPressed();

		switch(CharToPrint){
			case KEYPAD_BUTTON_NOT_PRESSED:
				break;
			case '?':
				HAL_7_SEGMENT_Replay();
				HAL_LCD_ClearScreen();
				break;
			default:
				HAL_7_SEGMENT_Increment();
				HAL_LCD_WriteChar(CharToPrint);
				break;
		}
    }
}
