/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Services/Platform_Types.h"
#include "../Services/stm32f103c6.h"
#include "../Services/Utils.h"
#include "../MCAL/Inc/GPIO.h"
#include "../MCAL/Inc/EXTI.h"
#include "../MCAL/Inc/USART.h"
#include "../MCAL/Inc/SPI.h"
#include "../MCAL/Inc/I2C.h"
#include "../MCAL/Inc/GPTM.h"
#include "../HAL/Inc/LCD.h"
#include "../HAL/Inc/keypad.h"
#include "../HAL/Inc/EEPROM.h"
#include "../HAL/Inc/SevenSegment.h"
#include "../HAL/Inc/Servo.h"


int main(void)
{
	GPIO_PinConfig_t led = {GPIOC,GPIO_PIN_13,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};
	GPIO_PinConfig_t IR1 = {GPIOB,GPIO_PIN_9,GPIO_MODE_INPUT_FLO,GPIO_OUTPUT_SPEED_NONE};

	MCAL_GPIO_Init(&led);
	MCAL_GPIO_TogglePin(&led);

	MCAL_GPIO_Init(&IR1);
	SERVO_Config_t ServoMotor1;
	ServoMotor1.SERVO_TimerPeripheral = TIM2;
	ServoMotor1.SERVO_Angle = SERVO_0;
	ServoMotor1.SERVO_ChannelIndex = CHANNEL_1_INDEX;

	HAL_SERVO_Init(&ServoMotor1);

	while(1)
	{
		if(MCAL_GPIO_ReadPin(&IR1) == GPIO_PIN_CLEAR)
		{
			MCAL_GPIO_WritePin(&led, GPIO_PIN_CLEAR);
			HAL_SERVO_WriteAngle(&ServoMotor1, SERVO_90);
		}
		else if(MCAL_GPIO_ReadPin(&IR1) == GPIO_PIN_SET)
		{
			MCAL_GPIO_WritePin(&led, GPIO_PIN_SET);
			HAL_SERVO_WriteAngle(&ServoMotor1, SERVO_0);
		}
//		HAL_SERVO_WriteAngle(&ServoMotor1, SERVO_45);
//		for(uint32_t i=0;i<500000;i++);
//		HAL_SERVO_WriteAngle(&ServoMotor1, SERVO_90);
//		for(uint32_t i=0;i<500000;i++);
//		HAL_SERVO_WriteAngle(&ServoMotor1, SERVO_135);
//		for(uint32_t i=0;i<500000;i++);
//		HAL_SERVO_WriteAngle(&ServoMotor1, SERVO_180);
//		for(uint32_t i=0;i<500000;i++);
//		HAL_SERVO_WriteAngle(&ServoMotor1, SERVO_0);
//		for(uint32_t i=0;i<500000;i++);
	}
}
