/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Services/Platform_Types.h"
#include "../Services/stm32f103c6.h"
#include "../MCAL/Inc/GPIO.h"
#include "../MCAL/Inc/EXTI.h"
#include "../MCAL/Inc/USART.h"
#include "../HAL/Inc/LCD.h"
#include "../HAL/Inc/keypad.h"
#include "../HAL/Inc/SevenSegment.h"

uint16_t character;
UART_Config_t uart1;

void my_wait(uint64_t x){
	for(int i=0;i<x;i++)
		for(int j=0;j<255;j++);
}

void UART1_IRQ_CallBack(void)
{

	MCAL_UART_Receive(&uart1, &character, UART_Polling_Disable);
	MCAL_UART_Transmit(&uart1, &character, UART_Polling_Enable);

}

int main(void)
{

	uart1.USARTx = USART1;
	uart1.USART_Mode = USART_MODE_TX_RX;
	uart1.USART_BaudRate = USART_BAUDRATE_115200;
	uart1.USART_WordLength = USART_WORD_LENGTH_8;
	uart1.USART_Parity = USART_PARITY_DISABLE;
	uart1.USART_StopBits = USART_STOP_BIT_1;
	uart1.USART_FlowControl = USART_FLOW_CONTROL_DISABLE;
	uart1.USART_IRQ_EN = USART_IE_RXNE;
	uart1.IRQ_CallBackPtr =UART1_IRQ_CallBack;

	MCAL_UART_Init(&uart1);
	MCAL_UART_GPIO_SetPins(&uart1);

    while (1)
    {

    }

}
