/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Services/stm32f103c6.h"
#include "../Services/Utils.h"
#include "../MCAL/Inc/EXTI.h"
#include "../CMSIS_V5/core_cm3.h"
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//									Functions Definitions
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-

void MainOS();
void TaskA(int a, int b, int c);
void TaskB(int a, int b, int c,int d);
int OS_SVC_Set(int a, int b, int SVC_ID);
void OS_SVC_Services(int* StackFramePointer);

//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//									Generic Macros
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-

#define OS_SET_PSP(addr) 			__asm volatile("mov r0,%0 \n\t"		\
													   "msr PSP,r0" 	\
													   :				\
													   :"r" (addr))

#define OS_SWITCH_SP_to_PSP() 		__asm volatile("mrs r0,CONTROL \n\t"	\
													"orr r0,r0,#0x2 \n\t" 	\
													"msr CONTROL,r0")

#define OS_SWITCH_SP_to_MSP() 		__asm volatile("mrs r0,CONTROL \n\t"	\
												   "and r0,r0,#0x5 \n\t" 	\
												   "msr CONTROL,r0")

#define OS_SWITCH_to_Pri()			__asm volatile("mrs r0,CONTROL \n\t"	\
													"lsr r0,#0x1 \n\t"		\
													"lsl r0,#0x1 \n\t"		\
													"msr CONTROL,r0")

#define OS_SWITCH_to_Unpri()		__asm volatile("mrs r0,CONTROL \n\t"	\
													"orr r0, r0,#0x1 \n\t"	\
													"msr CONTROL,r0")

#define OS_Generate_Exception() 	__asm volatile("SVC #0x3")

#define __ADD						(int)(0x1)
#define __SUB						(int)(0x2)
#define __MUL						(int)(0x3)

enum CPU_AccessLevel
{
	privileged,
	unprivileged
};

enum TaskFlag{
	NoTask_Running,
	TaskA_Running,
	TaskB_Running
};

enum TaskFlag Task_Flag = NoTask_Running;

//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//									Global Variables
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-s
int result = 0;
// Linker Script extern Value
extern unsigned int _estack;

// Main Stack Data
#define MAIN_STACK_SIZE		512	//512 bytes

unsigned int _S_MSP = (unsigned int) &_estack;
unsigned int _E_MSP;

// Task A Stack Data
#define TASK_A_STACK_SIZE	100	//100 bytes

unsigned int _S_PSP_TaskA;
unsigned int _E_PSP_TaskA;

// Task B Stack Data
#define TASK_B_STACK_SIZE	100	//100 bytes

unsigned int _S_PSP_TaskB;
unsigned int _E_PSP_TaskB;

//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//										ISR Handlers
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-

__attribute((naked)) void SVC_Handler()
{
	// Test, If Then Equal,
	__asm("TST LR,#0x4 \n\t"
			"ITE EQ \n\t"
			"MRSEQ R0,MSP \n\t"
			"MRSNE R0,PSP \n\t"
			"B OS_SVC_Services"
			);

}

void PendSV_Handler()
{
	__asm("nop");
}

void CallBackFunction(void)
{
	if(Task_Flag == NoTask_Running || Task_Flag == TaskB_Running)
	{
		Task_Flag = TaskA_Running;
	}
	else if(Task_Flag == TaskA_Running)
	{
		Task_Flag = TaskB_Running;
	}
}


int main(void)
{
//	EXTI_PinConfig_t EXTIConfig;
//	EXTIConfig.EXTI_GPIO_Port   = GPIOB;
//	EXTIConfig.EXTI_Input_Line 	= EXTI_9;
//	EXTIConfig.EXTI_Enable 		= EXTI_IRQ_ENABLE;
//	EXTIConfig.EXTI_Trigger		= EXTI_TRIGGER_RISING;
//	EXTIConfig.IRQ_CallBackPtr 	= CallBackFunction;
//	MCAL_EXTI_Init(&EXTIConfig);

//	MainOS();


	result = OS_SVC_Set(2, 3, __ADD);	// Add Call
	result = OS_SVC_Set(2, 3, __SUB);	// Subtract Call
	result = OS_SVC_Set(2, 3, __MUL);	// Multiply Call

	// PendSV Call
	result = OS_SVC_Set(0, 0, 4);

}

//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//									Functions Declarations
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-

void MainOS()
{
	//Initialize the Main Stack (Start & End)
	_E_MSP = _S_MSP - MAIN_STACK_SIZE;

	//Initialize Task A (Start & End)
	_S_PSP_TaskA = (_E_MSP - 8);
	_E_PSP_TaskA = (_S_PSP_TaskA - TASK_A_STACK_SIZE);

	//Initialize Task B (Start & End)
	_S_PSP_TaskB = (_E_PSP_TaskA - 8);
	_E_PSP_TaskB = (_S_PSP_TaskB - TASK_B_STACK_SIZE);

	while(1)
	{
		__asm("nop");
		if(Task_Flag == TaskA_Running)
		{
			// Set the PSP register = _S_PSP_TaskA
			OS_SET_PSP(_S_PSP_TaskA);
			// Make the SP point to PSP (SP -> PSP)
			OS_SWITCH_SP_to_PSP();
			// Switch from privileged to unprivileged
			OS_SWITCH_to_Unpri();


			// Activate the task
			TaskA(1, 2, 3);
			// Terminate the task


			// Switch from unprivileged to privileged
			OS_Generate_Exception();
			// Make the SP point to MSP (SP -> MSP)
			OS_SWITCH_SP_to_MSP();
		}
		else if(Task_Flag == TaskB_Running)
		{
			// Set the PSP register = _S_PSP_TaskB
			OS_SET_PSP(_S_PSP_TaskB);
			// Make the SP point to PSP (SP -> PSP)
			OS_SWITCH_SP_to_PSP();

			// Switch from privileged to unprivileged
			OS_SWITCH_to_Unpri();


			// Activate the task
			TaskB(1, 2, 3, 4);
			// Terminate the task


			// Switch from unprivileged to privileged
			OS_Generate_Exception();
			// Make the SP point to MSP (SP -> MSP)
			OS_SWITCH_SP_to_MSP();
		}
	}

}

void TaskA(int a, int b, int c)
{
	a = b;
	c = b;
	b = a;
	return;
}

void TaskB(int a, int b, int c, int d)
{
	a = b;
	c = b;
	b = d;
	d = a;
	return;
}

int OS_SVC_Set(int a, int b, int SVC_ID)
{
	int resultVal;

	switch(SVC_ID){
	case __ADD:
		// Add
		__asm ("SVC #0x1");
		break;
	case __SUB:
		// Subtract
		__asm ("SVC #0x2");
		break;
	case __MUL:
		// Multiply
		__asm ("SVC #0x3");
		break;
	case 4:
		__asm ("SVC #0x4");
		break;
	}

	__asm ("mov %[result],R0":[result] "=r" (resultVal));

	return resultVal;
}

void OS_SVC_Services(int* StackFramePointer)
{
	int Stacked_R0 		= StackFramePointer[0];		// R0
	int Stacked_R1 		= StackFramePointer[1];		// R1
	int Stacked_PC 		= StackFramePointer[6];		// PC

	unsigned char SVC_ID = *(((unsigned char*)Stacked_PC)-2);

	switch(SVC_ID)
	{
	case 1:
		// Add
		StackFramePointer[0] = Stacked_R0 + Stacked_R1;
		break;
	case 2:
		// Subtract
		StackFramePointer[0] = (Stacked_R0>Stacked_R1)?(Stacked_R0 - Stacked_R1):(Stacked_R1 - Stacked_R0);
		break;
	case 3:
		// Multiply
		StackFramePointer[0] = Stacked_R0 * Stacked_R1;
		break;
	case 4:
		// Set ICSR
		SCB->ICSR |= SCB_ICSR_PENDSVSET_Msk;
		break;
	}
}
