/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Services/Platform_Types.h"
#include "../Services/stm32f103c6.h"
#include "../MCAL/Inc/GPIO.h"
#include "../MCAL/Inc/EXTI.h"
#include "../MCAL/Inc/USART.h"
#include "../MCAL/Inc/SPI.h"
#include "../HAL/Inc/LCD.h"
#include "../HAL/Inc/keypad.h"
#include "../HAL/Inc/SevenSegment.h"

					/* @Config */
/*Choose the desired operation in SPI of you current MCU
 * OPTIONS:
 * --------
 * 1) MCU_1
 * 2) MCU_2
*/
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//										FUNCTIONS
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
void CloseALL(void);
void setup(void);
void SetColor(uint8_t i);
void NextColor(void);
void SendColor(void);
void UART1_IRQ_CallBack(void);

//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//									GLOBAL VARIABLES
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
uint16_t Led_Number = '0';
UART_Config_t uart1;
EXTI_PinConfig_t Button_changeColor;
EXTI_PinConfig_t Button_sendColor;
GPIO_PinConfig_t LED1 = {GPIOB,GPIO_PIN_3,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};
GPIO_PinConfig_t LED2 = {GPIOB,GPIO_PIN_4,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};
GPIO_PinConfig_t LED3 = {GPIOB,GPIO_PIN_5,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};
GPIO_PinConfig_t LED4 = {GPIOB,GPIO_PIN_6,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};
GPIO_PinConfig_t LED5 = {GPIOB,GPIO_PIN_7,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};
GPIO_PinConfig_t LED6 = {GPIOB,GPIO_PIN_8,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};

//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//										MAIN
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
int main(void)
{
	setup();
    while (1);
}

//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//								FUNCTIONS IMPLEMENTATION
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
void CloseALL(void)
{
	MCAL_GPIO_WritePin(&LED1, GPIO_PIN_SET);
	MCAL_GPIO_WritePin(&LED2, GPIO_PIN_SET);
	MCAL_GPIO_WritePin(&LED3, GPIO_PIN_SET);
	MCAL_GPIO_WritePin(&LED4, GPIO_PIN_SET);
	MCAL_GPIO_WritePin(&LED5, GPIO_PIN_SET);
	MCAL_GPIO_WritePin(&LED6, GPIO_PIN_SET);
}

void setup(void)
{

	//EXTI Config
	Button_changeColor.EXTI_Pin = EXTIPA1;
	Button_changeColor.EXTI_Trigger = EXTI_TRIGGER_RISING;
	Button_changeColor.EXTI_Enable = EXTI_IRQ_ENABLE;
	Button_changeColor.IRQ_CallBackPtr = NextColor;
	Button_sendColor.EXTI_Pin = EXTIPB0;
	Button_sendColor.EXTI_Trigger = EXTI_TRIGGER_FALLING;
	Button_sendColor.EXTI_Enable = EXTI_IRQ_ENABLE;
	Button_sendColor.IRQ_CallBackPtr = SendColor;
	//UART Config
	uart1.USARTx 			= USART1;
	uart1.USART_BaudRate 	= USART_BAUDRATE_115200;
	uart1.USART_WordLength 	= USART_WORD_LENGTH_8;
	uart1.USART_Parity 		= USART_PARITY_DISABLE;
	uart1.USART_StopBits 	= USART_STOP_BIT_1;
	uart1.USART_FlowControl = USART_FLOW_CONTROL_DISABLE;
	uart1.USART_Mode 		= USART_MODE_TX_RX;
	uart1.USART_IRQ_EN 		= USART_IE_RXNE;
	uart1.IRQ_CallBackPtr 	= UART1_IRQ_CallBack;

	//GPIO Init
	MCAL_GPIO_Init(&LED1);
	MCAL_GPIO_Init(&LED2);
	MCAL_GPIO_Init(&LED3);
	MCAL_GPIO_Init(&LED4);
	MCAL_GPIO_Init(&LED5);
	MCAL_GPIO_Init(&LED6);
	CloseALL();
	//EXTI Init
	MCAL_EXTI_Init(&Button_changeColor);
	MCAL_EXTI_Init(&Button_sendColor);
	//UART Init
	MCAL_UART_Init(&uart1);
	MCAL_UART_GPIO_SetPins(&uart1);
}

void SetColor(uint8_t i)
{
	switch(i){
		case '1':
			CloseALL();
			MCAL_GPIO_WritePin(&LED1, GPIO_PIN_CLEAR);
			break;
		case '2':
			CloseALL();
			MCAL_GPIO_WritePin(&LED2, GPIO_PIN_CLEAR);
			break;
		case '3':
			CloseALL();
			MCAL_GPIO_WritePin(&LED3, GPIO_PIN_CLEAR);
			break;
		case '4':
			CloseALL();
			MCAL_GPIO_WritePin(&LED4, GPIO_PIN_CLEAR);
			break;
		case '5':
			CloseALL();
			MCAL_GPIO_WritePin(&LED5, GPIO_PIN_CLEAR);
			break;
		case '6':
			CloseALL();
			MCAL_GPIO_WritePin(&LED6, GPIO_PIN_CLEAR);
			break;
	}
}

//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
//										CallBacks
//-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*--*-*-*-*-*-*-*-*-*-*-*-
void NextColor(void)
{
	Led_Number++;
	if(Led_Number == '7')
		Led_Number = '1';
	SetColor(Led_Number);
}

void SendColor(void)
{
	MCAL_UART_Transmit(&uart1, &Led_Number, UART_Polling_Enable);
}

void UART1_IRQ_CallBack(void)
{
	MCAL_UART_Receive(&uart1, &Led_Number, UART_Polling_Disable);
	SetColor(Led_Number);
}




