/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "..\Inc\Platform_Types.h"

/* register address */
#define RCC_BASE 			0x40021000
#define GPIOA_BASE 			0x40010800
#define AFIO_BASE			0x40010000
#define EXTI_BASE 			0x40010400


#define RCC_APB2ENR 		*((vuint32_t*) (RCC_BASE + 0x18))

#define GPIOA_CRL 			*((vuint32_t*) (GPIOA_BASE + 0x00))
#define GPIOA_CRH 			*((vuint32_t*) (GPIOA_BASE + 0x04))
#define GPIOA_ODR 			*((vuint32_t*) (GPIOA_BASE + 0x0C))

#define AFIO_EXTICR1		*((vuint32_t*) (GPIOA_BASE + 0x08))

#define EXTI_IMR 			*((vuint32_t*) (EXTI_BASE + 0x00))
#define EXTI_EMR 			*((vuint32_t*) (EXTI_BASE + 0x04))
#define EXTI_RTSR 			*((vuint32_t*) (EXTI_BASE + 0x08))
#define EXTI_FTSR 			*((vuint32_t*) (EXTI_BASE + 0x0C))
#define EXTI_SWIER			*((vuint32_t*) (EXTI_BASE + 0x10))
#define EXTI_PR				*((vuint32_t*) (EXTI_BASE + 0x14))


#define RCC_AFIOEN	(1<<0)
#define RCC_IOPAEN	(1<<2)
#define GPIOA_Pin13	(1UL<<13)


#define NVIC_ISER0 			*((vuint32_t*) (0xE000E100))

void Clock_Init(void){
	// Enable clock RCC for Alternating Function
	RCC_APB2ENR |= RCC_AFIOEN;
	// Enable clock RCC for Digital I/O
	RCC_APB2ENR |= RCC_IOPAEN;

}

void GPIO_Init(void){
	//Pin 13 Port A is Output
	GPIOA_CRH &= 0xff0fffff; // get them 0 first before change it
	GPIOA_CRH |= 0x00200000; // now we can set 2 safely

	//PortA Pin 0 is Floating
	GPIOA_CRL |= (1<<2);
}

int main(void)
{
	//Clock Initialization
	Clock_Init();

	//GPIO Initialization
	GPIO_Init();

	//Enable External Interrupt on PortA Pin0
	AFIO_EXTICR1 &= ~(0b1111<<0);

	//Enable EXTI Line 0 --> Mask 1
	EXTI_IMR |= (1<<0);

	//Enable Rising Edge Detection of Line 0
	EXTI_RTSR |= (1<<0);

	//Enable NVIC Irq 6 <<>> EXTI0
	NVIC_ISER0 |= (1<<6);

	while(1);

	return 0;
}

void EXTI0_IRQHandler(void){
	//Interrupt Happened --> PortAPin0 Rising Edge

	//Clear Pending Request To Avoid Re-Entering ISR
	EXTI_PR |= (1<<0);

	//Toggle Pin
	GPIOA_ODR ^= GPIOA_Pin13;
}
