/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "../Services/Platform_Types.h"
#include "../Services/stm32f103c6.h"
#include "../MCAL/Inc/GPIO.h"

void Clock_Init(void){
	//Enable CLock on Port A and Port B
	RCC_GPIOA_CLK_EN();
	RCC_GPIOB_CLK_EN();
}

void PushButtons_Init(void){
	/* GPIOA Configure Pin1 */
	GPIO_PinConfig_t PortA_Pin1_Config= {GPIO_PIN_1,GPIO_MODE_INPUT_FLO,GPIO_OUTPUT_SPEED_NONE};
	MCAL_GPIO_Init(GPIOA,&PortA_Pin1_Config);

	/* GPIOA Configure Pin13 */
	GPIO_PinConfig_t PortA_Pin13_Config= {GPIO_PIN_13,GPIO_MODE_INPUT_FLO,GPIO_OUTPUT_SPEED_NONE};
	MCAL_GPIO_Init(GPIOA,&PortA_Pin13_Config);

}

void LEDs_Init(void){
	/* GPIOB Configure Pin1 */
	GPIO_PinConfig_t PortB_Pin1_Config= {GPIO_PIN_1,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};
	MCAL_GPIO_Init(GPIOB,&PortB_Pin1_Config);
	MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, GPIO_PIN_SET); // Led is OFF

	/* GPIOB Configure Pin13 */
	GPIO_PinConfig_t PortB_Pin13_Config= {GPIO_PIN_13,GPIO_MODE_OUTPUT_PP,GPIO_OUTPUT_SPEED_10MHZ};
	MCAL_GPIO_Init(GPIOB,&PortB_Pin13_Config);
	MCAL_GPIO_WritePin(GPIOB, GPIO_PIN_13, GPIO_PIN_SET); // Led is OFF

}


int main(void)
{
    /* Initialization and Setup */
	Clock_Init();
	PushButtons_Init();
	LEDs_Init();

	while(1){
		//Check if Button1 is Pressed
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_CLEAR){
			//Toggle LED (PinB1)
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
			//Wait for Button Release
			while(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_1) == GPIO_PIN_CLEAR);
		}

		//Check if Button is Pressed (PinA13)
		if(MCAL_GPIO_ReadPin(GPIOA, GPIO_PIN_13) == GPIO_PIN_SET){
			//Toggle LED (PinB13)
			MCAL_GPIO_TogglePin(GPIOB, GPIO_PIN_13);
			//Delay
			for (int delay = 0 ; delay < 10000 ; delay ++);
		}
	}
}
